name: Test GitGotchi

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-pet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci

      - name: Build Action
        run: npm run build && npm run package

      - name: Run GitGotchi
        uses: ./
        with:
          token: ${{ secrets.USER_TOKEN }}
          pet_name: 'Demo Dragon'

      - name: Commit and Push
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
            git config user.name night-slayer18
            git config user.email samanuaia257@gmail.com
            git add README.md .github/gitgotchi
            git commit -m "Update GitGotchi Stats"
            git push
          fi
